export const HOME_PAGE = "Home";
export const CLAIM_PAGE = "Claim";
export const AUTH_PAGE = "Authenticator";
export const LOGIN_PAGE = "Login";
export const HOME_NAVIGATOR = "Home";
export const INCIDENT_PAGE = "Incident";
export const CONTACT_PAGE = "Contact Details";
export const INVOLVED_PAGE = "Involved Patry Details";
export const ADDPASSENGER_PAGE = "Add Passenger Details"
export const SUMMARY_PAGE = "Summary";
export const THANKYOU_PAGE ="Thankyou";